# Generated by Django 3.2 on 2022-09-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='is_active',
        ),
    ]
