# Generated by Django 3.2 on 2022-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_variation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
